export const employeeManagement_base_URL="http://localhost:8081/employeeManagement/"

export const employeeManagement_registration_getAllRegistration_URL="getAllRegistration"
export const employeeManagement_registration_getRegistration_URL="getRegistration/"
export const employeeManagement_registration_postRegistration_URL="addRegistration"
export const employeeManagement_registration_deleteRegistration_URL="deleteRegistration/"
export const employeeManagement_registration_updateRegistration_URL="updateRegistration"

export const employeeManagement_employeeDetails_getAllEmployeeDetails_URL="getAllEmployeeDetails"
export const employeeManagement_employeeDetails_getEmployeeDetails_URL="getEmployeeDetails/"
export const employeeManagement_employeeDetails_postEmployeeDetails_URL="postEmployeeDetails"
export const employeeManagement_employeeDetails_deleteEmployeeDetails_URL="deleteEmployeeDetails/"
export const employeeManagement_employeeDetails_updateEmployeeDetails_URL="updateEmployeeDetails"


export const employeeManagement_currentProject_getAllCurrentProject_URL="getAllCurrentProject"
export const employeeManagement_currentProject_getCurrentProjectByEmployeeId_URL="getCurrentProjectByEmployeeId/"
export const employeeManagement_currentProject_getCurrentProjectByCurrentProjectId_URL="getCurrentProjectByCurrentProjectId/"
export const employeeManagement_currentProject_postCurrentProject_URL="addCurrentProject"
export const employeeManagement_currentProject_deleteCurrentProject_URL="deleteCurrentProject/"
export const employeeManagement_currentProject_updateCurrentProject_URL="updateCurrentProject"


export const employeeManagement_priviousProject_getAllPriviousProject_URL="getAllPriviousProject"
export const employeeManagement_priviousProject_getPriviousProjectByEmployeeId="getPriviousProjectByEmployeeId/"
export const employeeManagement_priviousProject_getPriviousProjectByPriviousProjectId="getPriviousProjectByPriviousProjectId/"
export const employeeManagement_priviousProject_postPriviousProject="postPriviousProject"
export const employeeManagement_priviousProject_deletePriviousProject="deletePriviousProject/"
export const employeeManagement_priviousProject_updatePriviousProject="updatePriviousProject"


