export const employeeManagement_base_URL="http://localhost:8081/employeeManagement/"

export const employeeManagement_registration_getAllRegistration_URL="getAllRegistration"
export const employeeManagement_registration_getRegistration_URL="getRegistration/"
export const employeeManagement_registration_postRegistration_URL="addRegistration"
export const employeeManagement_registration_deleteRegistration_URL="deleteRegistration/"
export const employeeManagement_registration_updateRegistration_URL="updateRegistration"

export const employeeManagement_employeeDetails_getAllEmployeeDetails_URL="getAllEmployeeDetails"
export const employeeManagement_employeeDetails_getEmployeeDetails_URL="getEmployeeDetails/"
export const employeeManagement_employeeDetails_postEmployeeDetails_URL="postEmployeeDetails"
export const employeeManagement_employeeDetails_deleteEmployeeDetails_URL="deleteEmployeeDetails/"
export const employeeManagement_employeeDetails_updateEmployeeDetails_URL="updateEmployeeDetails"


export const employeeManagement_currentProject_getAllCurrentProject_URL="getAllCurrentProject"
export const employeeManagement_currentProject_getCurrentProjectByEmployeeId_URL="getCurrentProjectByEmployeeId/"
export const employeeManagement_currentProject_getCurrentProjectByCurrentProjectId_URL="getCurrentProjectByCurrentProjectId/"
export const employeeManagement_currentProject_postCurrentProject_URL="addCurrentProject"
export const employeeManagement_currentProject_deleteCurrentProject_URL="deleteCurrentProject/"
export const employeeManagement_currentProject_updateCurrentProject_URL="updateCurrentProject"


export const employeeManagement_priviousProject_getAllPriviousProject_URL="getAllPriviousProject"
export const employeeManagement_priviousProject_getPriviousProjectByEmployeeId="getPriviousProjectByEmployeeId/"
export const employeeManagement_priviousProject_getPriviousProjectByPriviousProjectId="getPriviousProjectByPriviousProjectId/"
export const employeeManagement_priviousProject_postPriviousProject="postPriviousProject"
export const employeeManagement_priviousProject_deletePriviousProject="deletePriviousProject/"
export const employeeManagement_priviousProject_updatePriviousProject="updatePriviousProject"



export const Instagram_logo_URL='public/imageges/instagram_logo.avif'
export const Linkdin_logo_URL='public/imageges/linkdin.png'
export const Github_logo_URL='public/imageges/github-logo.png'
export const Leetcode_logo_URL='public/imageges/leetcode.png'
export const Twitter_logo_URL='public/imageges/twitter-x-logo.png'
 

export const Instagram_Account_URL=''
export const Linkdin_Account_URL='https://www.linkedin.com/in/tribhuwan-pal-00553b215/'
export const Github_Account_URL='https://github.com/Tribhuwan2917'
export const Leetcode_Account_URL='https://leetcode.com/Tribhuwan_1729/'
export const Twitter_Account_URL=''
 
export const Hr_Management_URL='/hrManagement'
export const Manager_Management_URL='/managerManagent'
export const Team_Lead_Management_URL='/teamLeadManagement'
export const Senior_Manager_Management_URL='/seniorManagerManagement'
export const Project_Management_URL='/projectManagement'





