export const employeeManagement_base_URL="http://localhost:8081/employeeManagement/"

export const employeeManagement_registration_getAllRegistration_URL="getAllRegistration"
export const employeeManagement_registration_getRegistration_URL="getRegistration/"
export const employeeManagement_registration_postRegistration_URL="addRegistration"
export const employeeManagement_registration_deleteRegistration_URL="deleteRegistration/"
export const employeeManagement_registration_updateRegistration_URL="updateRegistration"

export const employeeManagement_employeeDetails_getAllEmployeeDetails_URL="getAllEmployeeDetails"
export const employeeManagement_employeeDetails_getEmployeeDetails_URL="getEmployeeDetails/"
export const employeeManagement_employeeDetails_postEmployeeDetails_URL="postEmployeeDetails"
export const employeeManagement_employeeDetails_deleteEmployeeDetails_URL="deleteEmployeeDetails/"
export const employeeManagement_employeeDetails_updateEmployeeDetails_URl="updateEmployeeDetails"
